environment: production
image_tag: production-build
secrets:
  API_KEY: {{secrets.API_KEY}}
  DATABASE_PASSWORD: {{secrets.DATABASE_PASSWORD}}
  TOKEN: {{secrets.TOKEN}}
  AWS_SECRET: {{secrets.AWS_SECRET}}
